# Setup

In [1]:
import pandas as pd
import json
import codecs
import itertools
import numpy as np
pd.set_option('display.max_columns', None)

# File Import

In [5]:
# data = json.load(codecs.open('BBGM_League_6_2040_preseason.json', 'r', 'utf-8-sig'))

In [157]:
# data_2110 = json.load(codecs.open('bbgm_lal_2110_playoffs_round_1_0-0.json', 'r', 'utf-8-sig'))

In [2]:
data = json.load(codecs.open('./data/bbgm_redo_2203_regular_season_42-20.json', 'r', 'utf-8-sig'))

# json_data exploration

In [5]:
draft_dict = {}

for player in data['players']:
    draft_dict

In [6]:
keys = itertools.cycle(data['players'][0].keys())

In [52]:
key = next(keys)
print(key)
data['players'][0][key]

gamesUntilTradable

0

In [45]:
'firstName', 'lastName', 'hof', 'ptModifier', 'ratings', 'stats', 
'weight', 'value', 'valueNoPot', 'valueFuzz', 'valueNoPotFuzz', 
'valueWithContract', 'pid', 'pfModifier', 'salaries', 'weight', 'awards', 'born'

('valueWithContract', 'pid', 'pfModifier', 'salaries', 'weight', 'awards')

In [64]:
lst = [x['valueWithContract'] for x in data['players']]
max_val = max(lst)
print(max_val)
try:
    max_index = lst.index(max_val)
    print(max_index)
except:
    max_index = -1

79.51412996207142
12907

In [69]:
data['players'][max_index]['draft']

{'round': 1,
 'pick': 8,
 'tid': 13,
 'year': 2194,
 'originalTid': 13,
 'pot': 65,
 'ovr': 46,
 'skills': []}

# DF Construction

- draft
- stats
- ratings

## Define df_create

In [5]:
def df_create(data, key_name):
    df = pd.DataFrame()
    for player in data['players']:
        try:
            df_concat = pd.DataFrame.from_dict(player[key_name])
        except ValueError:
            df_concat = pd.DataFrame.from_dict([player[key_name]])
        df_concat['pid'] = player['pid']
        df = pd.concat([df, df_concat])  
    return df

## df_draft

In [108]:
df_draft = pd.DataFrame()

for player in data['players']:
    df_concat = pd.DataFrame.from_dict([player['draft']])
    df_concat['pid'] = player['pid']
    df_draft = pd.concat([df_draft, df_concat])

In [130]:
df_draft.to_csv('draft.csv', index=False)

## df_ratings

In [120]:
df_ratings = pd.DataFrame()

for player in data['players']:
    df_concat = pd.DataFrame.from_dict(player['ratings'])
    df_concat['pid'] = player['pid']
    df_ratings = pd.concat([df_ratings, df_concat])

In [131]:
df_ratings.to_csv('ratings.csv', index=False)

## df_stats

In [136]:
df_stats = pd.DataFrame()

for player in data['players']:
    df_concat = pd.DataFrame.from_dict(player['stats'])
    df_concat['pid'] = player['pid']
    df_stats = pd.concat([df_stats, df_concat])

/Users/aemrich/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

In [144]:
df_stats.to_csv('stats.csv', index=False)

In [4]:
data['players'][0].keys()

dict_keys(['awards', 'born', 'college', 'contract', 'draft', 'face', 'firstName', 'freeAgentMood', 'gamesUntilTradable', 'hgt', 'hof', 'imgURL', 'injury', 'lastName', 'ptModifier', 'relatives', 'ratings', 'retiredYear', 'rosterOrder', 'salaries', 'stats', 'statsTids', 'tid', 'watch', 'weight', 'yearsFreeAgent', 'value', 'valueNoPot', 'valueFuzz', 'valueNoPotFuzz', 'valueWithContract', 'pid', 'diedYear'])

## df_born

In [20]:
df_born = df_create(data, 'born')

In [57]:
df_born.to_csv('./data/born.csv', index=False)

## df_weight

In [6]:
df_weight = df_create(data, 'weight')

In [7]:
df_weight.to_csv('./data/weight.csv', index=False)

## df_awards

In [55]:
df_awards = df_create(data, 'awards')

In [59]:
df_awards.to_csv('./data/awards.csv', index=False)

# JSON explorer

In [10]:
keys = itertools.cycle(data['players'][0].keys())

In [56]:
key = next(keys)
print(key)
data['players'][0][key]

college

''

# DFs Exploration

In [168]:
df_ratings[(df_ratings['pid'] == 4700)&(df_ratings['season'] == 2089)]

,diq,dnk,drb,endu,fg,ft,fuzz,hgt,ins,jmp,oiq,ovr,pos,pot,pss,reb,season,skills,spd,stre,tp,pid
12,100,100,79,84,55,77,-0.079151,68,100,43,91,85,FC,85,71,91,2089,"[3, A, Di, Dp, Po, Ps, R]",52,100,71,4700

In [173]:
df_ratings[(df_ratings['pid'] == 5590)]

,diq,dnk,drb,endu,fg,ft,fuzz,hgt,ins,jmp,oiq,ovr,pos,pot,pss,reb,season,skills,spd,stre,tp,pid
0,28,47,53,20,49,44,-0.825889,39,28,65,28,39,SG,61,48,52,2090,[],62,43,47,5590
1,52,57,58,39,61,54,-1.173005,39,34,67,49,57,PG,72,53,57,2091,[],64,51,60,5590
2,54,56,57,39,60,53,-1.085584,39,33,66,52,58,PG,70,52,56,2092,[],63,50,59,5590
3,65,69,62,53,67,66,-0.842307,39,46,68,66,67,G,77,57,61,2093,"[3, Dp]",65,67,71,5590
4,69,70,64,57,69,68,0.216459,39,48,69,71,70,G,74,59,62,2094,"[3, Di, Dp, Ps]",66,69,71,5590
5,74,78,68,63,76,76,0.172257,39,55,71,76,75,G,81,62,67,2095,"[3, A, Di, Dp, Ps]",68,74,78,5590
6,83,81,73,68,80,82,-0.026394,39,63,73,81,80,G,83,67,72,2096,"[3, A, B, Di, Dp, Ps, R]",70,81,86,5590
7,87,83,75,69,82,86,0.868356,39,67,75,85,82,G,85,72,73,2097,"[3, A, B, Di, Dp, Ps, R]",72,86,87,5590
8,88,83,75,69,83,86,0.967896,39,67,73,85,82,G,83,72,74,2098,"[3, A, B, Di, Dp, Ps, R]",73,86,88,5590
9,87,81,73,67,81,83,0.425526,39,66,69,83,80,G,81,70,72,2099,"[3, A, B, Di, Dp, Ps, R]",67,83,85,5590
10,85,79,71,65,79,81,0.247190,39,65,65,80,78,G,78,68,71,2100,"[3, A, Di, Dp, Ps]",64,81,83,5590
11,85,79,71,64,79,81,0.629594,39,65,60,80,77,G,77,68,71,2101,"[3, Di, Dp, Ps, R]",61,79,83,5590
12,84,78,70,59,78,80,0.059105,39,64,53,79,75,G,75,67,70,2102,"[3, Di, Ps]",52,77,82,5590
13,84,78,70,55,78,80,-0.049351,39,64,48,79,74,PG,74,67,70,2103,"[3, Di, Ps]",48,75,82,5590
14,82,76,68,49,77,78,-0.325594,39,62,40,76,70,SG,70,65,68,2104,"[3, Di, Ps]",38,73,80,5590
15,81,75,67,42,76,77,-0.917166,39,61,36,75,68,SG,68,64,67,2105,"[3, Ps]",34,70,79,5590
16,82,76,68,36,77,78,-1.107976,39,62,31,76,68,SG,68,65,68,2106,"[3, Ps]",28,69,79,5590
17,80,73,66,31,75,75,-0.594820,39,59,22,73,63,SG,63,63,66,2107,"[3, Ps]",17,64,76,5590

In [174]:
df_stats.sort_values('ewa', ascending=False)[0:10]#[['pid', 'ewa', 'season']]

,ast,astp,ba,blk,blkp,drb,drbp,drtg,dws,ewa,fg,fgAtRim,fgLowPost,fgMidRange,fga,fgaAtRim,fgaLowPost,fgaMidRange,ft,fta,gp,gs,min,orb,orbp,ortg,ows,per,pf,pid,playoffs,pm,pts,season,stl,stlp,tid,tov,tp,tpa,trbp,usgp,yearsWithTeam
22,606.0,31.051619,113.0,152.0,3.839306,890.0,26.717965,90.974571,10.019286,45.537804,903.0,259.0,291.0,5.0,1775.0,344.0,457.0,21.0,1079.0,1186.0,82.0,82.0,3486.088301,335.0,11.652336,142.193625,31.234491,43.870090,107.0,4700,False,1665.0,3233.0,2089.0,285.0,3.988281,16.0,287.0,348.0,953.0,19.738797,31.743272,12.0
10,316.0,16.583745,121.0,215.0,5.567840,817.0,26.010704,89.990810,9.743072,44.342036,962.0,332.0,300.0,2.0,1719.0,441.0,471.0,5.0,904.0,1007.0,82.0,82.0,3316.918047,318.0,11.737560,143.478578,28.967139,44.638218,91.0,4700,False,2082.0,3156.0,2083.0,262.0,3.886820,16.0,234.0,328.0,802.0,19.400828,31.160033,6.0
18,413.0,19.494516,94.0,152.0,3.754810,934.0,28.901314,90.957402,10.017884,41.930327,932.0,283.0,328.0,2.0,1681.0,381.0,496.0,3.0,895.0,1042.0,82.0,82.0,3448.707900,350.0,12.302719,141.925115,28.108084,41.597657,144.0,4700,False,2031.0,3078.0,2087.0,277.0,3.914506,16.0,255.0,319.0,801.0,21.130284,29.873536,10.0
20,424.0,24.013164,89.0,152.0,4.268408,793.0,27.126050,91.985140,8.558772,36.430955,777.0,241.0,259.0,5.0,1504.0,311.0,418.0,18.0,834.0,930.0,75.0,75.0,3121.665638,281.0,10.601531,137.053568,23.020003,40.371774,92.0,4700,False,1504.0,2660.0,2088.0,244.0,3.837917,16.0,257.0,272.0,757.0,19.268204,29.918455,11.0
12,729.0,36.777876,116.0,86.0,2.425467,551.0,18.362683,89.158340,9.770904,35.777871,799.0,175.0,96.0,103.0,1710.0,270.0,171.0,279.0,530.0,563.0,82.0,82.0,3195.834785,164.0,5.881385,139.457153,24.424133,38.877831,32.0,5590,False,1900.0,2553.0,2097.0,309.0,4.747999,12.0,168.0,425.0,990.0,12.350776,28.497325,7.0
7,170.0,8.863377,120.0,169.0,4.332382,616.0,18.752811,90.946817,9.494860,35.301663,990.0,228.0,73.0,199.0,2037.0,313.0,138.0,457.0,611.0,654.0,82.0,82.0,3390.664753,148.0,5.049067,134.044119,22.170016,37.208714,66.0,160,False,1690.0,3081.0,2022.0,230.0,3.352974,3.0,110.0,490.0,1129.0,12.290713,31.211601,5.0
16,276.0,14.698673,113.0,160.0,4.065111,821.0,26.051082,95.561910,7.606011,34.599907,789.0,244.0,276.0,3.0,1589.0,348.0,467.0,9.0,828.0,957.0,82.0,82.0,3393.460010,336.0,11.627357,133.213138,21.743130,36.667590,125.0,4700,False,812.0,2672.0,2086.0,250.0,3.698151,16.0,208.0,266.0,765.0,19.151707,28.893235,9.0
7,641.0,35.857572,106.0,73.0,1.939432,437.0,14.844734,103.576735,3.825775,33.960714,858.0,221.0,112.0,128.0,1791.0,306.0,224.0,288.0,528.0,607.0,80.0,80.0,3128.880210,143.0,5.245201,135.259891,23.192177,37.770553,30.0,6420,False,941.0,2641.0,2107.0,200.0,3.197062,6.0,145.0,397.0,973.0,10.229084,30.945479,2.0
12,475.0,26.926713,91.0,212.0,5.714508,499.0,17.136834,98.315639,6.251141,33.728338,730.0,266.0,153.0,23.0,1435.0,358.0,276.0,79.0,754.0,846.0,82.0,82.0,3150.375774,191.0,6.754333,141.447167,23.060983,37.949156,46.0,4752,False,961.0,2502.0,2085.0,193.0,3.066103,11.0,180.0,288.0,722.0,12.021595,27.249941,7.0
12,762.0,45.544532,97.0,93.0,2.556870,503.0,17.365977,98.358267,6.122410,33.585588,851.0,178.0,126.0,107.0,1878.0,240.0,258.0,287.0,501.0,568.0,79.0,79.0,3129.106615,165.0,5.940872,131.702764,21.657500,37.467375,42.0,6420,False,919.0,2643.0,2110.0,203.0,3.228662,6.0,189.0,440.0,1093.0,11.773336,32.190049,5.0

In [151]:
df_stats[df_stats['pid'] == 8360][['ewa', 'season']]

          ewa  season
0    1.571574  2130.0
1   -0.006746  2130.0
2    6.265702  2131.0
3    0.111235  2131.0
4    4.444023  2132.0
5   11.271509  2133.0
6    7.749030  2134.0
7   10.861944  2135.0
8    0.133157  2135.0
9   12.026302  2136.0
10   6.086698  2137.0
11   7.950598  2138.0
12   3.273414  2139.0
13   0.874894  2140.0

In [152]:
df_ratings[df_ratings['hgt'] == 100][['ovr','season']]

    ovr  season
0    45    2129
1    48    2130
2    52    2131
3    55    2132
4    59    2133
5    59    2134
6    62    2135
7    59    2136
8    56    2137
9    54    2138
10   48    2139
11   42    2140
12   35    2141